version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t build/

  build:
    commands:
      - echo "Copying source files..."
      - cp *.py build/
      - echo "Creating deployment package..."
      - cd build
      - zip -r ../lambda-function.zip .
      - cd ..

artifacts:
  files:
    - lambda-function.zip
  name: lambda-deployment-$(date +%Y%m%d-%H%M%S)
