AWSTemplateFormatVersion: '2010-09-09'
Description: SavorSwipe Recipe Processing Lambda Function

Parameters:
  SourceCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda source code
    Default: savorswipe-lambda-code

  SourceCodeKey:
    Type: String
    Description: S3 key for Lambda source code zip
    Default: lambda-function.zip

  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

  GoogleSearchId:
    Type: String
    Description: Google Custom Search Engine ID
    NoEcho: true

  GoogleSearchKey:
    Type: String
    Description: Google Custom Search API Key
    NoEcho: true

  RecipeBucketName:
    Type: String
    Description: S3 Bucket name for recipe storage
    Default: savorswipe-recipes

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${RecipeBucketName}'
                  - !Sub 'arn:aws:s3:::${RecipeBucketName}/*'

  # Lambda Function
  RecipeProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: savorswipe-recipe-add
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref SourceCodeBucket
        S3Key: !Ref SourceCodeKey
      Description: Multi-file recipe processing with OCR and image search
      MemorySize: 1024
      Timeout: 600
      Environment:
        Variables:
          API_KEY: !Ref OpenAIApiKey
          SEARCH_ID: !Ref GoogleSearchId
          SEARCH_KEY: !Ref GoogleSearchKey
          AWS_S3_BUCKET: !Ref RecipeBucketName

  # Function URL
  RecipeProcessorFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt RecipeProcessorFunction.Arn
      AuthType: NONE
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        MaxAge: 300

  # Permission for Function URL
  RecipeProcessorFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RecipeProcessorFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref RecipeProcessorFunction

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt RecipeProcessorFunction.Arn

  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt RecipeProcessorFunctionUrl.FunctionUrl
