[project]
name = "savorswipe-backend"
version = "0.1.0"
description = "AWS Lambda backend for SavorSwipe recipe processing and image search"
requires-python = ">=3.9"

dependencies = [
    "boto3>=1.26.0",
    "requests>=2.28.0",
    "python-dotenv>=0.20.0",
    "openai>=0.27.0",
    "Pillow>=9.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "moto>=4.1.0",
    "requests-mock>=1.9.0",
    "ruff>=0.1.0",
]

[tool.ruff]
# Moderate linting configuration for Python backend

# Python version target
target-version = "py39"

# Line length
line-length = 100

# Include all Python files
include = ["*.py"]

# Exclude directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    ".pytest_cache",
    ".moto",
]

# Moderate rule selection
select = [
    "E",    # Errors
    "W",    # Warnings
    "F",    # PyFlakes (undefined names, unused imports)
    "I",    # isort (import sorting)
    "N",    # pep8-naming
    "D",    # pydocstyle (docstrings)
]

ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    "E501",  # Line too long (handled by formatter)
    "W503",  # Line break before binary operator
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
# Ensure proper import sorting
known-first-party = [
    "lambda_function",
    "upload",
    "search_image",
    "ocr",
    "embeddings",
    "embedding_generator",
    "duplicate_detector",
    "handlepdf",
]
